import AppKit
import Combine

/// A single saved clip.
struct ClipItem: Identifiable, Codable, Equatable {
    let id: UUID
    let text: String
    let date: Date
    var isPinned: Bool

    init(text: String, isPinned: Bool = false) {
        self.id = UUID()
        self.text = text
        self.date = Date()
        self.isPinned = isPinned
    }

    // Custom decode so history saved by older versions (no isPinned) still loads.
    enum CodingKeys: String, CodingKey { case id, text, date, isPinned }
    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(UUID.self, forKey: .id)
        text = try c.decode(String.self, forKey: .text)
        date = try c.decode(Date.self, forKey: .date)
        isPinned = try c.decodeIfPresent(Bool.self, forKey: .isPinned) ?? false
    }
}

/// Watches the system pasteboard and keeps a de-duplicated history of copied text.
final class ClipboardManager: ObservableObject {
    @Published private(set) var history: [ClipItem] = []

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private let maxItems: Int
    private let storageKey = "clipboard_history"

    // Types other apps use to say "don't store this" (passwords, transient values).
    private let concealedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    init(maxItems: Int = 50) {
        self.maxItems = maxItems
        self.lastChangeCount = pasteboard.changeCount
        load()
        startMonitoring()
    }

    // macOS has no "pasteboard changed" notification, so we poll changeCount.
    private func startMonitoring() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.checkClipboard()
        }
    }

    private func checkClipboard() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        // Skip anything an app marked as a password / secret / transient value.
        let currentTypes = pasteboard.types ?? []
        if concealedTypes.contains(where: { currentTypes.contains($0) }) { return }

        guard let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        addItem(text)
    }

    private func addItem(_ text: String) {
        // If the same text exists, move it to the top but keep its pinned state.
        if let existing = history.first(where: { $0.text == text }) {
            history.removeAll { $0.text == text }
            history.insert(existing, at: 0)
        } else {
            history.insert(ClipItem(text: text), at: 0)
        }
        trim()
        save()
    }

    /// Keep all pinned clips plus the most recent unpinned ones up to maxItems.
    private func trim() {
        let pinnedCount = history.filter { $0.isPinned }.count
        let allowedUnpinned = max(0, maxItems - pinnedCount)
        var unpinnedSeen = 0
        history = history.filter { item in
            if item.isPinned { return true }
            unpinnedSeen += 1
            return unpinnedSeen <= allowedUnpinned
        }
    }

    /// Writes a clip back to the system clipboard so the user can paste it.
    func copyToClipboard(_ item: ClipItem) {
        pasteboard.clearContents()
        pasteboard.setString(item.text, forType: .string)
        lastChangeCount = pasteboard.changeCount     // don't re-capture our own write
    }

    func togglePin(_ item: ClipItem) {
        guard let idx = history.firstIndex(where: { $0.id == item.id }) else { return }
        history[idx].isPinned.toggle()
        trim()
        save()
    }

    func delete(_ item: ClipItem) {
        history.removeAll { $0.id == item.id }
        save()
    }

    /// Clears everything except pinned clips.
    func clearHistory() {
        history.removeAll { !$0.isPinned }
        save()
    }

    // MARK: - Persistence (UserDefaults)

    private func save() {
        if let data = try? JSONEncoder().encode(history) {
            UserDefaults.standard.set(data, forKey: storageKey)
        }
    }

    private func load() {
        guard let data = UserDefaults.standard.data(forKey: storageKey),
              let decoded = try? JSONDecoder().decode([ClipItem].self, from: data) else { return }
        history = decoded
    }
}
